import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  list: []
};

const taskSlice = createSlice({
  name: 'tasks',
  initialState,
  reducers: {
    addTask: (state, action) => {
      state.list.push({
        id: Date.now(),
        text: action.payload,
        completed: false
      });
    },
    toggleTask: (state, action) => {
      const task = state.list.find(t => t.id === action.payload);
      if (task) {
        task.completed = !task.completed;
      }
    }
  }
});

// Export the action creators generated by createSlice. These functions will be used to dispatch actions to the store.
export const { addTask, toggleTask } = taskSlice.actions;

// Export the reducer to be used in the store configuration. The reducer will handle the state updates for the 
// tasks based on the defined actions and return the updated state when actions are dispatched.
export default taskSlice.reducer; 